services:
  web-pipeline:
    image: khadijajumani/knowledge-hub:latest
    container_name: knowledge_hub_pipeline_web
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://db-pipeline:27017/university-notes
    depends_on:
      - db-pipeline

  db-pipeline:
    image: mongo:latest
    container_name: knowledge_hub_pipeline_db
    volumes:
      - mongodb_pipeline_data:/data/db

volumes:
  mongodb_pipeline_data:
