services:
  web:
    image: khadijajumani/knowledge-hub:latest
    container_name: knowledge_hub_web
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://db:27017/university-notes
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: knowledge_hub_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
