apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: database
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 32017 # Explicit NodePort assignment (range 30000-32767)
  selector:
    app: database
